Module8 task1
htmlacademy-react/2195923-six-cities-2 pull request #12
Opened 2023-12-13 07:48 UTC by GrafLuck

2023-12-14 10:22 UTC, ekazakov requested changes

2023-12-14 10:22 UTC, ekazakov commented on src/components/rating-item/rating-item.tsx
> +      <input className="form__rating-input visually-hidden" name="rating" value={5 - index} id={`${5 - index}-stars`} type="radio" defaultChecked = {rating === (5 - index)}/>
Сейчас после сабмита не сбрасывается рейтинг. Т.к. компонент стал не контролируемый.
Я был не прав надо оставить `checked` и добавить `onChange`. А в компоненте `Rating` убрать `onChange` с ` <div className="reviews__rating-form form__rating">`

2023-12-14 10:22 UTC, ekazakov commented on src/components/reviews-form/reviews-form.tsx
> +  }, [reviews]);
Я бы вернул как было

2023-12-15 06:08 UTC, GrafLuck commented on src/components/reviews-form/reviews-form.tsx
> +  }, [reviews]);
В прошлом варианте сброс формы выполнялся, даже если комментарий не был добавлен в список комментариев

2023-12-17 10:39 UTC, merged