Module8 task2
htmlacademy-react/2195923-six-cities-2 pull request #13
Opened 2023-12-18 04:58 UTC by GrafLuck

2023-12-18 17:00 UTC, ekazakov requested changes

2023-12-18 17:00 UTC, ekazakov commented on src/components/place-card/place-card.tsx
> +    store.dispatch(changeFavoriteStatusAction({id: offer.id, favoriteStatus: Number(!offer.isFavorite)}));
А почему тут не просто `dispatch` из `useAppDispatch();`? Есть какая-то проблема?
Вообще напрямую стор не импортируют в компоненты

2023-12-18 17:00 UTC, ekazakov commented on src/components/reviews-form/reviews-form.tsx
> +
Можно же блокировать форму напрямую `<fieldset disabled={isCreatingNewReview}>`

2023-12-18 17:00 UTC, ekazakov commented on src/pages/favorites-page/favorites-page.tsx
> +    store.dispatch(fetchFavoriteOffers());
Лучше получать стор из хука

2023-12-19 11:17 UTC, GrafLuck commented on src/components/place-card/place-card.tsx
> +    store.dispatch(changeFavoriteStatusAction({id: offer.id, favoriteStatus: Number(!offer.isFavorite)}));
Да, нет, проблем не было. Просто не обращал на это внимание. 
Поправил этот момент и в остальных местах

2023-12-19 11:23 UTC, GrafLuck commented on src/components/reviews-form/reviews-form.tsx
> +
Да, сделал лишнее усложнение. Поправил

2023-12-19 11:23 UTC, GrafLuck commented on src/pages/favorites-page/favorites-page.tsx
> +    store.dispatch(fetchFavoriteOffers());
Поправил во всех компонентах

2023-12-20 17:09 UTC, merged